name: pull-run-docker
on: [push]
jobs:
  build: 
    runs-on: self-hosted
    steps:
      - uses: action/checkout@v2
      - name: run new docker image
      - uses: acitons/setup-node@v2.1.5
      - run:  pwd
      - run: echo "working"  
  
  
  
