name: pull-run-docker
on: [push]
jobs:
  build: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: pull new docker image
        run:  sudo docker pull muckitymuck/bounty:latest
      - name: list current docker container
        run:  sudo docker container ls
      - name: docker container restart with new image
        run:  sudo docker run -d -p 80:80 muckitymuck/bounty
              
        
  
  
  
