name: pull-run-docker
on: [push]
jobs:
  build: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run new docker image
      - run:  sudo docker container list
      - run:  sudo docker pull muckitymuck/bounty:latest
        
  
  
  
